name: verticV
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cudatoolkit=11.0.221
  - freetype=2.10.4
  - intel-openmp=2021.4.0
  - jpeg=9b
  - libpng=1.6.37
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ninja=1.10.2
  - olefile=0.46
  - openssl=1.1.1l
  - pillow=8.4.0
  - pip=21.0.1
  - python=3.8.12
  - pytorch=1.7.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - torchvision=0.8.2
  - typing_extensions=3.10.0.2
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.0
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - charset-normalizer==2.0.7
    - colorama==0.4.4
    - cycler==0.11.0
    - idna==3.3
    - kiwisolver==1.3.2
    - matplotlib==3.4.3
    - numpy==1.21.4
    - opencv-python==4.5.3.56
    - pandas==1.3.4
    - protobuf==3.19.1
    - pyparsing==3.0.5
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==6.0
    - requests==2.26.0
    - scipy==1.7.2
    - seaborn==0.11.2
    - tqdm==4.62.3
    - urllib3==1.26.7
